module.exports = {
	apps: [
		{
			name: "molq-api",
			cwd: "/home/cuyvps/apps/molq/apps/api",
			script: "./node_modules/.bin/tsx",
			args: "src/server.ts",
			interpreter: "none",
			env: {
				NODE_ENV: "production",
				HOST: "127.0.0.1",
				PORT: "8070",
			},
			autorestart: true,
			max_memory_restart: "500M",
			kill_timeout: 12000,
			exp_backoff_restart_delay: 100,
			time: true,
		},
		{
			name: "molq-indexer",
			cwd: "/home/cuyvps/apps/molq/apps/indexer",
			script: "./node_modules/.bin/ponder",
			args: "start --port 8071 --schema molq_v2",
			interpreter: "none",
			env: {
				NODE_ENV: "production",
				CHOKIDAR_USEPOLLING: "true",
				CHOKIDAR_INTERVAL: "1000",
			},
			autorestart: true,
			max_memory_restart: "1G",
			kill_timeout: 12000,
			exp_backoff_restart_delay: 100,
			time: true,
		},
		{
			name: "molq-agent",
			cwd: "/home/cuyvps/apps/molq/apps/api",
			script: "./node_modules/.bin/tsx",
			args: "src/agent-worker.ts",
			interpreter: "none",
			env: {
				NODE_ENV: "production",
			},
			autorestart: true,
			cron_restart: "*/30 * * * *",
			max_memory_restart: "500M",
			kill_timeout: 12000,
			exp_backoff_restart_delay: 100,
			time: true,
		},
		{
			name: "molq-monitor",
			cwd: "/home/cuyvps/apps/molq/apps/api",
			script: "./node_modules/.bin/tsx",
			args: "src/monitor.ts",
			interpreter: "none",
			env: {
				NODE_ENV: "production",
			},
			autorestart: true,
			max_memory_restart: "200M",
			exp_backoff_restart_delay: 100,
			time: true,
		},
	],
};
